apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  backstage.io/kubernetes-id: sample-argocd-app

resources:
#  - project.yaml
#  - rolebindings.yaml
  - sample-argocd-app-deploy.yaml
  - sample-argocd-app-service.yaml
  - sample-argocd-app-route.yaml
